# .github/workflows/release.yml
name: Build and Release

on:
  push:
    paths:
      - 'package.json'
      - '**/*.ts'
      - '**/*.js'
      - '.npmignore'

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Pack project
        id: pack-project
        run: |
          FILE=$(npm pack)
          echo "file=$FILE" >> $GITHUB_OUTPUT

      - name: Read version from package.json
        id: package_version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version detected: $VERSION"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.package_version.outputs.version }}
          name: v${{ steps.package_version.outputs.version }}
          files: ${{ steps.pack-project.outputs.file }}
          body: |
            Release for version v${{ steps.package_version.outputs.version }}.
            - Built from commit ${{ github.sha }}
            - Triggered by a push to `${{ github.ref }}`

            Changes since last release:
            $(git log $(git describe --tags --abbrev=0)..HEAD --oneline)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
